// Builds themes/ogtrips/assets/icons/sprite.svg from the Lucide icons used by the approved design.
// Icon names = every data-lucide="…" in .claude/design/*.html and the design's main.js, plus EXTRA_ICONS
// (icons the WordPress templates need that the static design does not show).
// lucide-static is pinned to the version the design loads from unpkg, so glyphs match exactly.
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire( import.meta.url );
const root = dirname( dirname( fileURLToPath( import.meta.url ) ) );
const designDir = join( root, '../.claude/design' );
const iconsDir = join( dirname( require.resolve( 'lucide-static/package.json' ) ), 'icons' );
const outFile = join( root, 'themes/ogtrips/assets/icons/sprite.svg' );

// camera, landmark: offered in wp-admin icon pickers (photo stop, culture trip type).
const EXTRA_ICONS = [ 'camera', 'landmark' ];

const sources = [
	...readdirSync( designDir )
		.filter( ( f ) => f.endsWith( '.html' ) )
		.map( ( f ) => join( designDir, f ) ),
	join( designDir, 'assets/js/main.js' ),
];

const names = new Set( EXTRA_ICONS );
for ( const file of sources ) {
	for ( const m of readFileSync( file, 'utf8' ).matchAll( /data-lucide="([a-z0-9-]+)"/g ) ) {
		names.add( m[ 1 ] );
	}
}

const symbols = [ ...names ].sort().map( ( name ) => {
	const svg = readFileSync( join( iconsDir, `${ name }.svg` ), 'utf8' );
	const inner = svg
		.replace( /^[\s\S]*?<svg[^>]*>/, '' )
		.replace( /<\/svg>\s*$/, '' )
		.replace( /\s*\n\s*/g, '' );
	// Stroke/fill attributes sit on the outer <svg> (see ogtrips_icon()) so the design's CSS can override them.
	return `<symbol id="${ name }" viewBox="0 0 24 24">${ inner }</symbol>`;
} );

mkdirSync( dirname( outFile ), { recursive: true } );
writeFileSync(
	outFile,
	`<svg xmlns="http://www.w3.org/2000/svg">\n<!-- Lucide icons (ISC licence), lucide.dev. Generated by scripts/build-icons.mjs — do not edit. -->\n${ symbols.join( '\n' ) }\n</svg>\n`
);
console.log( `icons: ${ names.size } symbols → ${ outFile }` );
