<?php
/**
 * DEMO CONTENT. The trips follow the client's own itineraries (resources/: The Soul of Ladakh,
 * Shimla–Manali, Winter Kashmir, Spiti Winter Expedition). Reviews, social handles, phone,
 * address and most prices are FAKE placeholders: change them, or click "Remove demo content",
 * before launch. Photos: Unsplash (free licence), downloaded into the Media Library on import.
 *
 * @package ogtrips-core
 */

defined( 'ABSPATH' ) || exit;

$u = static function ( $id ) {
	return 'https://images.unsplash.com/photo-' . $id . '?auto=format&fit=crop&w=1800&q=78';
};

$img = [
	'ladakh-road'  => $u( '1581793745862-99fde7fa73d2' ),
	'ladakh-peaks' => $u( '1506905925346-21bda4d32df4' ),
	'flags'        => $u( '1571401835393-8c5f35328320' ),
	'mountains'    => $u( '1464822759023-fed622ff2c3b' ),
	'roadtrip'     => $u( '1469854523086-cc02fe5d8800' ),
	'rohtang'      => $u( '1593181629936-11c609b8db9b' ),
	'forest'       => $u( '1605649487212-47bdab064df7' ),
	'snow-trek'    => $u( '1626621341517-bbf3d9990a23' ),
	'shimla'       => $u( '1597074866923-dc0589150358' ),
	'dal-lake'     => $u( '1595815771614-ade9d652a65d' ),
	'meadow'       => $u( '1598091383021-15ddea10925d' ),
	'neha'         => $u( '1438761681033-6461ffad8d80' ),
	'priya'        => $u( '1494790108377-be9c29b29330' ),
	'rahul'        => $u( '1507003211169-0a1dd7228f2d' ),
	'sneha'        => $u( '1517841905240-472988babdf9' ),
	'reel'         => $u( '1530789253388-582c481c54b0' ),
	'packing'      => $u( '1488646953014-85cb44e25828' ),
];

$p = static function ( $text ) {
	return '<p>' . $text . '</p>';
};

$cancellation = $p( 'More than 30 days before travel: 25% of the tour cost is charged. 15–30 days before: 50%. Less than 15 days before: 100%.' );
$payment      = $p( '50% advance to confirm the booking; the balance is due 30 days before the date of travel. No payment is taken on this website.' );

return [
	'images'       => $img,

	'destinations' => [
		'ladakh'  => [ 'Ladakh', 'High passes, turquoise lakes and ancient monasteries on the roof of India.' ],
		'kashmir' => [ 'Kashmir', 'Houseboats on Dal Lake, Mughal gardens and the meadows of Gulmarg, Sonmarg and Pahalgam.' ],
		'manali'  => [ 'Manali', 'Snow at Solang and Atal Tunnel, old temples and apple orchards in the Kullu valley.' ],
		'shimla'  => [ 'Shimla', 'The colonial hill station: Mall Road, the Ridge, Kufri and Mashobra.' ],
		'spiti'   => [ 'Spiti', 'The cold desert: cliff-top monasteries, the highest villages and endless winter skies.' ],
	],

	'expert'       => [
		'login'       => 'neha',
		'first_name'  => 'Neha',
		'last_name'   => 'Sharma',
		'description' => 'Neha has led OgTrips departures across Ladakh, Spiti and Kashmir since 2019 and still stops for butter tea at every dhaba on the Manali–Leh highway. (Demo profile — replace with your own team.)',
		'photo'       => 'neha',
		'byline_role' => 'OgTrips trip captain',
		'specialty'   => 'Himalaya specialist',
		'reply_time'  => 'replies in ~5 min',
	],

	'trips'        => [
		[
			'slug'    => 'soul-of-ladakh',
			'title'   => 'The Soul of Ladakh: Leh, Nubra Valley & Pangong Lake',
			'image'   => 'ladakh-road',
			'dest'    => 'ladakh',
			'types'   => [ 'adventure', 'friends', 'culture' ],
			'excerpt' => 'Six days through ancient monasteries, Khardung La, the dunes of Nubra and the turquoise waters of Pangong Lake, with two nights in Leh to acclimatise.',
			'content' => $p( 'Experience the timeless beauty of Ladakh on a thoughtfully curated six-day journey through ancient monasteries, dramatic mountain passes, high-altitude deserts and pristine alpine lakes. Two relaxed nights in Leh for acclimatisation, then across the legendary Khardung La into the Nubra Valley, through the Shyok Valley to Pangong Lake, and a final evening back in Leh.' ),
			'fields'  => [
				'title_display'   => 'The Soul of *Ladakh*: Leh, Nubra & Pangong',
				'short_title'     => 'The Soul of Ladakh',
				'location_label'  => 'Ladakh, India',
				'badge'           => '#1 Bestseller',
				'badge_style'     => 'sun',
				'badge_icon'      => 'award',
				'is_bestseller'   => 1,
				'bestseller_rank' => 1,
				'route_stops'     => [
					[ 'label' => 'Leh', 'days' => 'Day 1–2' ],
					[ 'label' => 'Nubra Valley', 'days' => 'Day 3' ],
					[ 'label' => 'Pangong Lake', 'days' => 'Day 4' ],
					[ 'label' => 'Leh', 'days' => 'Day 5–6' ],
				],
				'highlights'      => [
					[ 'icon' => 'mountain', 'text' => 'Khardung La Pass (5,359 m)' ],
					[ 'icon' => 'sparkles', 'text' => 'Diskit Monastery & Maitreya Buddha' ],
					[ 'icon' => 'tent', 'text' => 'Hunder sand dunes & Bactrian camel safari' ],
					[ 'icon' => 'waves', 'text' => 'Pangong Lake sunset & stargazing' ],
					[ 'icon' => 'droplets', 'text' => 'Indus & Zanskar river confluence' ],
					[ 'icon' => 'sunrise', 'text' => 'Shey Palace & Thiksey Monastery' ],
				],
				'duration_days'   => 6,
				'duration_nights' => 5,
				'group_min'       => 2,
				'group_max'       => 6,
				'best_time'       => 'May – September',
				'pace'            => 'moderate',
				'stays_label'     => 'Deluxe hotels & lakeside stay',
				'rating'          => 4.9,
				'review_count'    => 128,
				'price_from'      => 58075,
				'departures'      => [
					[ 'date' => '20270515', 'seats_left' => 6 ],
					[ 'date' => '20270612', 'seats_left' => 8 ],
					[ 'date' => '20270710', 'seats_left' => 8 ],
				],
				'days'            => [
					[ 'title' => 'Arrival in Leh – a gentle introduction to the Himalayas', 'location' => 'Leh · 3,500 m', 'image' => 'ladakh-peaks', 'description' => $p( 'Arrive at Kushok Bakula Rimpochee Airport. A private transfer takes you to your boutique hotel, with the morning spent resting and acclimatising. In the afternoon, visit Shanti Stupa for panoramic views over Leh and the Indus Valley, then Leh Palace, the former royal residence of the Namgyal dynasty, and stroll through the lively Leh Market.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Hotel Zomeday or similar' ], [ 'icon' => 'car', 'text' => 'Airport transfer' ], [ 'icon' => 'utensils', 'text' => 'Dinner' ] ] ],
					[ 'title' => 'Along the ancient Silk Route', 'location' => 'Leh → Nimmu → Alchi · approx. 140 km', 'image' => 'flags', 'description' => $p( 'Visit the Hall of Fame Museum, Gurudwara Pathar Sahib and the fascinating Magnetic Hill. Drive to Nimmu, where the Indus and Zanskar rivers meet, and on to Alchi Monastery, one of Ladakh’s oldest, renowned for its ancient murals and wood carvings. Return to Leh in the evening.' ), 'tags' => [ [ 'icon' => 'coffee', 'text' => 'Breakfast & dinner' ], [ 'icon' => 'car', 'text' => 'Private Ertiga' ] ] ],
					[ 'title' => 'Leh to Nubra Valley – across Khardung La', 'location' => 'Khardung La · Diskit · Hunder · approx. 120 km', 'image' => 'ladakh-road', 'description' => $p( 'Cross the legendary Khardung La Pass (5,359 m) and descend into the Nubra Valley. Optional ATV rides, zipline and go-karting at T-Mode Adventure Park (extra cost), then Diskit Monastery and its towering Maitreya Buddha, and the Hunder sand dunes with an optional Bactrian camel safari.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Organic Boutique Hunder' ], [ 'icon' => 'tent', 'text' => 'Camel safari (optional)' ] ] ],
					[ 'title' => 'Nubra Valley to Pangong Lake via Shyok', 'location' => 'Shyok Valley · Pangong · approx. 170 km', 'image' => 'mountains', 'description' => $p( 'Journey through the spectacular Shyok River Valley to the iconic Pangong Lake. Spend the afternoon on the lakeshore as its colours change, then a sunset followed by one of the clearest star-filled skies in the Himalayas.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Thangzing House' ], [ 'icon' => 'sparkles', 'text' => 'Stargazing' ] ] ],
					[ 'title' => 'Pangong Lake to Leh – monasteries of the Indus valley', 'location' => 'Chang La · Shey · Thiksey · approx. 225 km', 'image' => 'ladakh-peaks', 'description' => $p( 'Wake early for sunrise over Pangong, then return to Leh via the Chang La Pass. Visit Shey Palace, the royal summer residence, and the magnificent Thiksey Monastery. Final evening in Leh’s market, cafés and artisan shops.' ), 'tags' => [ [ 'icon' => 'sunrise', 'text' => 'Pangong sunrise' ], [ 'icon' => 'utensils', 'text' => 'Breakfast & dinner' ] ] ],
					[ 'title' => 'Departure from Leh', 'location' => 'Leh Airport', 'image' => 'roadtrip', 'description' => $p( 'After breakfast, transfer to Leh Airport for your onward journey — carrying memories of sacred monasteries, high passes and crystal-clear lakes. Jullay!' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Airport transfer' ] ] ],
				],
				'stays'           => [
					[ 'name' => 'Hotel Zomeday, Leh (or similar)', 'nights' => 3, 'room' => 'Deluxe room', 'image' => 'ladakh-peaks' ],
					[ 'name' => 'Organic Boutique Hunder', 'nights' => 1, 'room' => 'Deluxe room', 'image' => 'ladakh-road' ],
					[ 'name' => 'Thangzing House, Pangong', 'nights' => 1, 'room' => 'Deluxe room', 'image' => 'mountains' ],
				],
				'incl_icons'      => [ 'bed-double', 'utensils', 'car', 'mountain' ],
				'included'        => [ 'Comfortable private transport (Ertiga)', 'Welcome drinks on arrival at hotels', 'Accommodation in deluxe rooms', 'Breakfast & dinner at all hotels', 'Professional driver, all tolls & parking', 'Inner Line Permit', 'Oxygen cylinder in the vehicle' ],
				'excluded'        => [ 'Flights to and from Leh', 'Personal expenses', 'Adventure activities & entry charges', 'Hotel add-on services', 'Extra transport due to natural calamities' ],
				'gallery'         => [ 'ladakh-road', 'flags', 'ladakh-peaks', 'mountains', 'roadtrip', 'snow-trek' ],
				'faqs'            => [
					[ 'question' => 'Is the altitude a problem?', 'answer' => $p( 'The first two days stay in and around Leh so your body can acclimatise before the high passes. An oxygen cylinder travels in the vehicle. Drink plenty of water and go slow.' ) ],
					[ 'question' => 'What is the cancellation policy?', 'answer' => $cancellation ],
					[ 'question' => 'How do I pay?', 'answer' => $payment ],
					[ 'question' => 'Can I customise this itinerary?', 'answer' => $p( 'Yes — add nights, upgrade hotels or travel privately. Mention it in your enquiry and a trip expert will tailor it.' ) ],
				],
			],
		],
		[
			'slug'    => 'shimla-manali',
			'title'   => 'Shimla & Manali: Kufri, Solang Valley & Atal Tunnel',
			'image'   => 'rohtang',
			'dest'    => 'manali',
			'dest2'   => 'shimla',
			'types'   => [ 'family', 'honeymoon' ],
			'excerpt' => 'Six days in Himachal’s favourite hill stations — Mall Road and Kufri in Shimla, then Solang Valley, Atal Tunnel and Sissu from Manali.',
			'content' => $p( 'Himachal’s two favourite hill stations in one easy week. Kufri, Mashobra and the Mall Road in Shimla, then over to Manali for snow at Solang Valley, the Atal Tunnel and Sissu, the 450-year-old Hadimba Devi temple and the old village of Vashisht.' ),
			'fields'  => [
				'title_display'   => 'Shimla & *Manali*: Kufri, Solang Valley & Atal Tunnel',
				'short_title'     => 'Shimla & Manali',
				'location_label'  => 'Himachal Pradesh, India',
				'badge'           => 'Family favourite',
				'badge_style'     => 'plain',
				'badge_icon'      => 'baby',
				'is_bestseller'   => 1,
				'bestseller_rank' => 2,
				'route_stops'     => [
					[ 'label' => 'Chandigarh', 'days' => 'Day 1' ],
					[ 'label' => 'Shimla', 'days' => 'Day 1–2' ],
					[ 'label' => 'Manali', 'days' => 'Day 3–5' ],
					[ 'label' => 'Chandigarh', 'days' => 'Day 6' ],
				],
				'highlights'      => [
					[ 'icon' => 'mountain', 'text' => 'Kufri & Mahasu Peak' ],
					[ 'icon' => 'camera', 'text' => 'Mall Road & the Ridge, Shimla' ],
					[ 'icon' => 'sparkles', 'text' => 'Solang Valley, Atal Tunnel & Sissu' ],
					[ 'icon' => 'droplets', 'text' => 'Vashisht hot springs' ],
					[ 'icon' => 'heart', 'text' => 'Hadimba Devi temple' ],
					[ 'icon' => 'ticket', 'text' => 'Paragliding & cable car (optional)' ],
				],
				'duration_days'   => 6,
				'duration_nights' => 5,
				'group_min'       => 2,
				'group_max'       => 12,
				'best_time'       => 'March – June, Dec – Feb for snow',
				'pace'            => 'easy',
				'stays_label'     => 'Handpicked hotels',
				'rating'          => 4.8,
				'review_count'    => 176,
				'days'            => [
					[ 'title' => 'Chandigarh to Shimla', 'location' => 'Chandigarh → Shimla', 'image' => 'shimla', 'description' => $p( 'Pick-up from Chandigarh airport or railway station and a scenic drive up to Shimla. Overnight in Shimla.' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Private transfer' ], [ 'icon' => 'bed-double', 'text' => 'Hotel in Shimla' ] ] ],
					[ 'title' => 'Shimla sightseeing: Kufri, Mashobra & Mall Road', 'location' => 'Kufri · Mashobra · Shimla', 'image' => 'snow-trek', 'description' => $p( 'Visit Kufri, 13 km from Shimla — yak and horse rides, and a trek up to Mahasu Peak for the adventurous (a ski retreat in winter). Then Mashobra, and an evening stroll on the famous Mall Road. Time permitting: Jakhu temple, Rashtrapati Bhavan and a walk to the Ridge.' ), 'tags' => [ [ 'icon' => 'coffee', 'text' => 'Breakfast' ], [ 'icon' => 'mountain', 'text' => 'Kufri' ] ] ],
					[ 'title' => 'Shimla to Manali', 'location' => 'Kullu · Manali', 'image' => 'forest', 'description' => $p( 'Drive to Manali, visiting the Kullu shawl factory and Vaishno Devi temple on the way. Check in for dinner and the night.' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Scenic drive' ], [ 'icon' => 'utensils', 'text' => 'Dinner' ] ] ],
					[ 'title' => 'Solang Valley, Atal Tunnel & Sissu', 'location' => 'Solang · Atal Tunnel · Sissu', 'image' => 'rohtang', 'description' => $p( 'A full-day excursion to Solang Valley, the Atal Tunnel and Sissu. Solang is known for paragliding, zorbing, snow scooters and ATV rides, with a cable car up Solang Nala. On the way back, a dip in the hot springs at Vashisht.' ), 'tags' => [ [ 'icon' => 'ticket', 'text' => 'Activities at own cost' ], [ 'icon' => 'droplets', 'text' => 'Hot springs' ] ] ],
					[ 'title' => 'Manali sightseeing', 'location' => 'Hadimba · Old Manali · Vashisht', 'image' => 'forest', 'description' => $p( 'Visit the 450-year-old Hadimba Devi temple, the Tibetan monastery, Club House, Van Vihar and the handicraft centre, then walk up to the old Vashisht village. Optional: Rohtang Pass if open (charges paid directly).' ), 'tags' => [ [ 'icon' => 'heart', 'text' => 'Hadimba temple' ], [ 'icon' => 'utensils', 'text' => 'Dinner' ] ] ],
					[ 'title' => 'Manali to Chandigarh', 'location' => 'Manali → Chandigarh', 'image' => 'roadtrip', 'description' => $p( 'After breakfast, drive back to Chandigarh for your onward journey.' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Drop at airport / station' ] ] ],
				],
				'incl_icons'      => [ 'bed-double', 'utensils', 'car', 'ticket' ],
				'included'        => [ '5 nights in handpicked hotels', 'Daily breakfast and dinner', 'Private car with driver for all transfers & sightseeing', 'Tolls, parking and driver allowances' ],
				'excluded'        => [ 'Travel to Chandigarh', 'Adventure activities (paragliding, zorbing, cable car)', 'Rohtang Pass permit & charges', 'Personal expenses' ],
				'gallery'         => [ 'rohtang', 'shimla', 'forest', 'snow-trek' ],
				'faqs'            => [
					[ 'question' => 'Will we see snow?', 'answer' => $p( 'From December to February snow is likely at Kufri and Solang Valley; in spring and summer you will find snow higher up beyond the Atal Tunnel.' ) ],
					[ 'question' => 'What is the cancellation policy?', 'answer' => $cancellation ],
				],
			],
		],
		[
			'slug'    => 'winter-kashmir',
			'title'   => 'Winter Kashmir: Pahalgam, Gulmarg, Sonmarg & Srinagar',
			'image'   => 'dal-lake',
			'dest'    => 'kashmir',
			'types'   => [ 'honeymoon', 'family' ],
			'excerpt' => 'Six days through the valleys of Pahalgam, the meadows of Gulmarg and Sonmarg, and a shikara ride on Dal Lake.',
			'content' => $p( 'Paradise in six days: the Valley of Shepherds at Pahalgam, Aru and Betaab valleys, the Mughal gardens and a shikara ride on Dal Lake in Srinagar, and full days in the meadows of Gulmarg and Sonmarg.' ),
			'fields'  => [
				'title_display'   => 'Winter *Kashmir*: Pahalgam, Gulmarg & Sonmarg',
				'short_title'     => 'Winter Kashmir',
				'location_label'  => 'Kashmir, India',
				'badge'           => 'Honeymoon pick',
				'badge_style'     => 'plain',
				'badge_icon'      => 'heart',
				'is_bestseller'   => 1,
				'bestseller_rank' => 3,
				'route_stops'     => [
					[ 'label' => 'Srinagar', 'days' => 'Day 1' ],
					[ 'label' => 'Pahalgam', 'days' => 'Day 1–2' ],
					[ 'label' => 'Srinagar', 'days' => 'Day 3–6' ],
				],
				'highlights'      => [
					[ 'icon' => 'sprout', 'text' => 'Saffron fields of Pampore' ],
					[ 'icon' => 'mountain', 'text' => 'Aru & Betaab valleys' ],
					[ 'icon' => 'sailboat', 'text' => 'Shikara ride on Dal Lake' ],
					[ 'icon' => 'sparkles', 'text' => 'Gulmarg gondola (optional)' ],
					[ 'icon' => 'droplets', 'text' => 'Sonmarg, the Meadow of Gold' ],
					[ 'icon' => 'camera', 'text' => 'Shalimar & Nishat Mughal gardens' ],
				],
				'duration_days'   => 6,
				'duration_nights' => 5,
				'group_min'       => 2,
				'group_max'       => 10,
				'best_time'       => 'December – February for snow; April – October',
				'pace'            => 'easy',
				'stays_label'     => 'Hotels in Pahalgam & Srinagar',
				'rating'          => 4.9,
				'review_count'    => 142,
				'days'            => [
					[ 'title' => 'Srinagar to Pahalgam', 'location' => 'Srinagar → Pahalgam · 94 km', 'image' => 'meadow', 'description' => $p( 'Arrive at Srinagar airport and drive to Pahalgam, the Valley of Shepherds, on the banks of the Lidder River. On the way, the saffron fields and the Awantipora cricket-bat factories.' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Airport pick-up' ], [ 'icon' => 'bed-double', 'text' => 'Hotel in Pahalgam' ] ] ],
					[ 'title' => 'Pahalgam: Aru, Chandanwari & Betaab valley', 'location' => 'Lidder valley', 'image' => 'snow-trek', 'description' => $p( 'A day to explore the Lidder valley: Aru village, starting point for the Kolahoi glacier treks; Chandanwari, famous for snow sledging; and Betaab valley, where the Bollywood film was shot.' ), 'tags' => [ [ 'icon' => 'mountain', 'text' => 'Valleys' ], [ 'icon' => 'coffee', 'text' => 'Breakfast' ] ] ],
					[ 'title' => 'Pahalgam to Srinagar: Mughal gardens & shikara', 'location' => 'Srinagar · Dal Lake', 'image' => 'dal-lake', 'description' => $p( 'Back to Srinagar for the Mughal gardens on the banks of Dal Lake — Shalimar Bagh, Nishat Bagh, Chashme Shahi and the botanical garden — and an evening shikara ride to Nehru Park.' ), 'tags' => [ [ 'icon' => 'sailboat', 'text' => 'Shikara ride' ] ] ],
					[ 'title' => 'Day trip to Gulmarg', 'location' => 'Gulmarg · 2,730 m', 'image' => 'meadow', 'description' => $p( 'A full day in Gulmarg, the Meadow of Flowers, with walks across the meadows beneath snow-capped peaks. Pony ride or the gondola up to Khilanmarg at your own cost.' ), 'tags' => [ [ 'icon' => 'ticket', 'text' => 'Gondola (optional)' ] ] ],
					[ 'title' => 'Day trip to Sonmarg', 'location' => 'Sonmarg · 84 km', 'image' => 'mountains', 'description' => $p( 'A full day at Sonmarg, the Meadow of Gold, on the Srinagar–Leh road — glaciers, fir and birch forests and a gushing river. Dinner and overnight in Srinagar.' ), 'tags' => [ [ 'icon' => 'utensils', 'text' => 'Dinner' ] ] ],
					[ 'title' => 'Depart Srinagar', 'location' => 'Srinagar Airport', 'image' => 'dal-lake', 'description' => $p( 'After breakfast, transfer to the airport for your flight home.' ), 'tags' => [ [ 'icon' => 'plane', 'text' => 'Airport drop' ] ] ],
				],
				'incl_icons'      => [ 'bed-double', 'utensils', 'car', 'sailboat' ],
				'included'        => [ '5 nights in hotels (2 Pahalgam, 3 Srinagar)', 'Daily breakfast and dinner', 'Private car for all transfers and sightseeing', 'Shikara ride on Dal Lake' ],
				'excluded'        => [ 'Flights to Srinagar', 'Gondola and pony rides', 'Local union cabs in Pahalgam & Sonmarg', 'Personal expenses' ],
				'gallery'         => [ 'dal-lake', 'meadow', 'snow-trek', 'mountains' ],
				'faqs'            => [
					[ 'question' => 'Can we stay on a houseboat?', 'answer' => $p( 'Yes — swap a Srinagar night for a deluxe houseboat on Dal Lake. Ask in your enquiry.' ) ],
					[ 'question' => 'What is the cancellation policy?', 'answer' => $cancellation ],
				],
			],
		],
		[
			'slug'    => 'spiti-winter-expedition',
			'title'   => 'Spiti Winter Expedition: Chitkul, Tabo, Kaza & Kalpa',
			'image'   => 'flags',
			'dest'    => 'spiti',
			'types'   => [ 'adventure', 'friends' ],
			'excerpt' => 'Nine days into the cold desert — Chitkul, Nako, Tabo, Key Monastery, the highest post office in the world at Hikkim, and Kalpa.',
			'content' => $p( 'Nine days into India’s cold desert in winter. From Shimla through Kinnaur to Chitkul, the last village in India, then Nako, Tabo and Kaza — Key Monastery on its hilltop, Chicham Bridge, Langza’s Buddha, Komic and the world’s highest post office at Hikkim — and back via Kalpa under the Kinner Kailash range.' ),
			'fields'  => [
				'title_display'   => 'Spiti *Winter* Expedition',
				'short_title'     => 'Spiti Winter Expedition',
				'location_label'  => 'Spiti Valley, India',
				'badge'           => 'Selling fast',
				'badge_style'     => 'coral',
				'badge_icon'      => 'flame',
				'is_bestseller'   => 1,
				'bestseller_rank' => 4,
				'route_stops'     => [
					[ 'label' => 'Shimla', 'days' => 'Day 1–2' ],
					[ 'label' => 'Sangla', 'days' => 'Day 2' ],
					[ 'label' => 'Tabo', 'days' => 'Day 3' ],
					[ 'label' => 'Kaza', 'days' => 'Day 4–6' ],
					[ 'label' => 'Kalpa', 'days' => 'Day 7' ],
				],
				'highlights'      => [
					[ 'icon' => 'mountain', 'text' => 'Chitkul, the last village in India' ],
					[ 'icon' => 'sparkles', 'text' => 'Key Monastery' ],
					[ 'icon' => 'heart', 'text' => 'Hikkim, highest post office in the world' ],
					[ 'icon' => 'droplets', 'text' => 'Nako Lake' ],
					[ 'icon' => 'camera', 'text' => 'Chicham Bridge' ],
					[ 'icon' => 'sunrise', 'text' => 'Kinner Kailash views from Kalpa' ],
				],
				'duration_days'   => 9,
				'duration_nights' => 8,
				'group_min'       => 4,
				'group_max'       => 12,
				'best_time'       => 'December – March (winter)',
				'pace'            => 'challenging',
				'stays_label'     => 'Homestays & hotels',
				'rating'          => 4.8,
				'review_count'    => 64,
				'departures'      => [
					[ 'date' => '20261218', 'seats_left' => 5 ],
					[ 'date' => '20270115', 'seats_left' => 9 ],
					[ 'date' => '20270212', 'seats_left' => 10 ],
				],
				'days'            => [
					[ 'title' => 'Delhi to Shimla', 'location' => '347 km · overnight Volvo or cab', 'image' => 'roadtrip', 'description' => $p( 'Board a Volvo bus or cab from Delhi at night; after 7–8 hours you reach Shimla the following day.' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Overnight journey' ] ] ],
					[ 'title' => 'Shimla to Sangla & Chitkul', 'location' => '220 km · 2,270 m → 2,630 m', 'image' => 'snow-trek', 'description' => $p( 'Drive to Sangla or Rakcham via Rampur and Karcham. In the evening, visit Chitkul, the last village in India.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Homestay / hotel' ], [ 'icon' => 'utensils', 'text' => 'Dinner' ] ] ],
					[ 'title' => 'Sangla to Tabo via Nako', 'location' => '90 km · 2,630 m → 3,280 m', 'image' => 'mountains', 'description' => $p( 'After breakfast, leave for Tabo, stopping at Nako village and Nako Lake, and Gue Monastery if time permits.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Homestay in Tabo' ], [ 'icon' => 'utensils', 'text' => 'Breakfast & dinner' ] ] ],
					[ 'title' => 'Tabo to Kaza', 'location' => '50 km · 3,280 m → 3,800 m', 'image' => 'flags', 'description' => $p( 'Visit Tabo Monastery, then Dhankar Monastery, the Pin Valley entrance and Lingti waterfall on the way to Kaza.' ), 'tags' => [ [ 'icon' => 'sparkles', 'text' => 'Monasteries' ] ] ],
					[ 'title' => 'Kaza sightseeing: Langza, Komic & Hikkim', 'location' => '3,800 m → 4,590 m', 'image' => 'ladakh-peaks', 'description' => $p( 'Langza and its Buddha statue overlooking the valley, Komic, one of the most remote villages, and Hikkim, home to the highest post office in the world.' ), 'tags' => [ [ 'icon' => 'heart', 'text' => 'Send a postcard' ] ] ],
					[ 'title' => 'Key Monastery & Chicham Bridge', 'location' => 'Kaza', 'image' => 'flags', 'description' => $p( 'The iconic Key Monastery, perched on a hill above the Spiti River, and Chicham Bridge, Asia’s highest suspension bridge. Back to Kaza for the night.' ), 'tags' => [ [ 'icon' => 'camera', 'text' => 'Chicham Bridge' ] ] ],
					[ 'title' => 'Kaza to Kalpa', 'location' => '160 km · 3,280 m → 2,960 m', 'image' => 'mountains', 'description' => $p( 'An early start for Kalpa in Kinnaur, with views of the Kinner Kailash range. Evening at Suicide Point and the Reckong Peo market.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Hotel in Kalpa' ] ] ],
					[ 'title' => 'Kalpa to Shimla and depart', 'location' => '324 km', 'image' => 'shimla', 'description' => $p( 'Wake to views of the Kalpa valley, then drive back to Shimla, arriving late evening to board your bus or cab to Delhi.' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Overnight journey' ] ] ],
					[ 'title' => 'Arriving in Delhi', 'location' => 'Delhi', 'image' => 'roadtrip', 'description' => $p( 'Arrive in Delhi early in the morning with a treasure trove of memories from the cold desert of India.' ), 'tags' => [ [ 'icon' => 'heart', 'text' => 'Trip ends' ] ] ],
				],
				'incl_icons'      => [ 'bed-double', 'utensils', 'car', 'tent' ],
				'included'        => [ 'Delhi–Shimla–Delhi Volvo or cab', 'Homestays and hotels as listed', 'Breakfast and dinner from Day 2 to Day 8', 'Transport for the whole route', 'Trip captain throughout' ],
				'excluded'        => [ 'Lunches', 'Personal expenses', 'Entry fees', 'Extra costs due to snow or road closures' ],
				'gallery'         => [ 'flags', 'mountains', 'snow-trek', 'ladakh-peaks' ],
				'faqs'            => [
					[ 'question' => 'How cold does it get?', 'answer' => $p( 'Winter nights in Kaza can drop below −15°C. Pack thermals, a down jacket, gloves and warm boots — we share a full packing list after booking.' ) ],
					[ 'question' => 'What is the cancellation policy?', 'answer' => $cancellation ],
				],
			],
		],
	],

	'reviews'      => [
		[ 'Priya Sharma', 'Mumbai', '20260601', 'google', 'priya', 'soul-of-ladakh', 'Every transfer was on time and every hotel was better than the photos. The acclimatisation days in Leh made all the difference — Pangong at sunset was unreal.' ],
		[ 'Rahul Kapoor', 'Delhi', '20260201', 'tripadvisor', 'rahul', 'spiti-winter-expedition', 'Spiti in winter was the adventure of a lifetime. The homestays were warm, the driver knew every road, and Key Monastery in the snow is something I will never forget.' ],
		[ 'Ananya & Mihir', 'Bengaluru', '20260101', 'google', 'neha', 'winter-kashmir', 'Our honeymoon in Kashmir was flawless — snow in Gulmarg, a shikara ride on Dal Lake and the 24/7 WhatsApp support is genuinely 24/7.' ],
		[ 'Sneha Iyer', 'Pune', '20260501', 'google', 'sneha', 'shimla-manali', 'Travelled with my parents and two kids — the pace was just right for everyone. Solang Valley and the Atal Tunnel were the highlight of our year.' ],
	],

	'moments'      => [
		[ '@wanderwithriya', 'reel', 'big', 'video', '0:42', '12.4k', '98k' ],
		[ '@arjun.clicks', 'dal-lake', 'normal', 'image', '', '2.1k', '' ],
		[ '@ladakh.diaries', 'ladakh-road', 'tall', 'video', '0:28', '8.7k', '' ],
		[ '@mihir_ananya', 'meadow', 'normal', 'image', '', '5.3k', '' ],
		[ '@roadtrip.rahul', 'roadtrip', 'normal', 'image', '', '3.9k', '' ],
		[ '@desi.nomad', 'flags', 'normal', 'image', '', '1.8k', '' ],
		[ '@sneha.travels', 'rohtang', 'normal', 'video', '1:05', '6.2k', '' ],
		[ '@kavya.goes', 'shimla', 'normal', 'image', '', '2.6k', '' ],
	],

	'guides'       => [
		[
			'slug'    => 'ladakh-travel-guide',
			'title'   => 'The complete Ladakh guide for *first-timers*',
			'image'   => 'ladakh-peaks',
			'dest'    => 'ladakh',
			'topic'   => 'destination-guide',
			'excerpt' => 'When to go, how to acclimatise, permits, getting around, what it costs and what to pack — from the OgTrips trip captains.',
			'fields'  => [
				'cover_caption'    => 'Start slow in Leh — the passes will still be there on day three.',
				'glance_best_time' => 'May – September',
				'glance_budget'    => '₹4,000 – ₹12,000',
				'glance_length'    => '6 – 8 days',
				'glance_visa'      => 'Inner Line Permit',
			],
			'blocks'  => 'guide',
		],
		[
			'slug'    => 'spiti-in-winter',
			'title'   => 'Spiti in winter: what to expect',
			'image'   => 'snow-trek',
			'dest'    => 'spiti',
			'topic'   => 'seasonal',
			'excerpt' => 'Frozen rivers, −15°C nights and almost no tourists — how to do the cold desert safely.',
			'blocks'  => 'short',
		],
		[
			'slug'    => 'kashmir-houseboat-guide',
			'title'   => 'Dal Lake houseboat or hotel in Srinagar?',
			'image'   => 'dal-lake',
			'dest'    => 'kashmir',
			'topic'   => 'destination-guide',
			'excerpt' => 'Two very different ways to stay in Srinagar — and how to choose.',
			'blocks'  => 'short',
		],
		[
			'slug'    => 'pack-for-the-himalayas',
			'title'   => 'How to pack for a Himalayan road trip',
			'image'   => 'packing',
			'dest'    => '',
			'topic'   => 'travel-tips',
			'excerpt' => 'Layers, medicines and the small things that make long mountain drives comfortable.',
			'blocks'  => 'short',
		],
	],

	// Footer pages. Created only if a page with the same slug does not exist yet; never removed.
	// Text in [brackets] / marked PLACEHOLDER must be replaced (privacy text needs a legal review).
	'pages'        => [
		[
			'slug'    => 'about-us',
			'title'   => 'About us',
			'content' => [
				[ 'p', 'PLACEHOLDER — replace with the founders’ own story. OgTrips plans trips across Ladakh, Kashmir, Manali, Shimla and Spiti with handpicked stays, day-by-day plans and a real human on call 24/7.' ],
				[ 'h2', 'Why we started' ],
				[ 'p', 'We were tired of copy-paste holidays. Every trip we sell is one our team has travelled — the roads, the hotels and the small detours that make a trip memorable.' ],
				[ 'h2', 'How we work' ],
				[ 'ul', [ 'Itineraries planned by people who have been there', 'Transparent pricing — what is included is listed, and so is what is not', 'A trip captain on WhatsApp before, during and after your trip' ] ],
			],
		],
		[
			'slug'    => 'faqs',
			'title'   => 'FAQs',
			'content' => [
				[ 'h2', 'Do I pay on this website?' ],
				[ 'p', 'No. Send an enquiry or message us on WhatsApp — a trip expert confirms the plan and price with you first.' ],
				[ 'h2', 'How do I confirm a booking?' ],
				[ 'p', 'A 50% advance confirms your booking; the balance is due 30 days before the date of travel.' ],
				[ 'h2', 'Can you customise a trip?' ],
				[ 'p', 'Yes — add nights, upgrade hotels, change the route or travel privately. Mention it in your enquiry.' ],
				[ 'h2', 'Do I need permits for Ladakh or Spiti?' ],
				[ 'p', 'Indian citizens need an Inner Line Permit for areas such as Nubra Valley and Pangong Lake. We arrange the permits for every trip that needs them.' ],
				[ 'h2', 'What is the cancellation policy?' ],
				[ 'p', 'See our Cancellation policy page for the full terms.' ],
			],
		],
		[
			'slug'    => 'cancellation-policy',
			'title'   => 'Cancellation policy',
			'content' => [
				[ 'p', 'These terms apply to all OgTrips packages unless your confirmation says otherwise.' ],
				[ 'h2', 'Cancellation charges' ],
				[ 'ul', [ 'More than 30 days before the date of travel: 25% of the total tour cost.', '15 to 30 days before the date of travel: 50% of the total tour cost.', 'Less than 15 days before the date of travel: 100% of the total tour cost.' ] ],
				[ 'h2', 'Payment' ],
				[ 'p', 'A 50% advance is required to confirm the booking. The balance of the total tour cost must be paid 30 days before the date of travel.' ],
				[ 'h2', 'Changes beyond our control' ],
				[ 'p', 'Extra costs caused by natural calamities, road closures or weather (for example extra nights or transport) are not included in the package cost.' ],
			],
		],
		[
			'slug'    => 'privacy-policy',
			'title'   => 'Privacy policy',
			'privacy' => true,
			'content' => [
				[ 'p', 'PLACEHOLDER — have this reviewed before launch. [Company legal name], [address].' ],
				[ 'h2', 'What we collect' ],
				[ 'p', 'When you send an enquiry we store the details you enter (name, phone, email, travel plans) so a trip expert can reply. WhatsApp enquiries are handled under WhatsApp’s own privacy policy.' ],
				[ 'h2', 'How we use it' ],
				[ 'p', 'Only to plan and confirm your trip. We never sell or share your details for marketing.' ],
				[ 'h2', 'Your rights' ],
				[ 'p', 'Ask us at [email address] to see, correct or delete your details.' ],
			],
		],
	],

	// Demo blog posts (Blog menu) — same article layout as the tour guides.
	'posts'        => [
		[
			'slug'     => 'first-time-in-ladakh-diary',
			'title'    => 'Our first group of the season in Ladakh',
			'image'    => 'ladakh-road',
			'dest'     => 'ladakh',
			'category' => 'Travel stories',
			'excerpt'  => 'Snow on Khardung La in May, butter tea in Nubra and a full moon over Pangong — notes from our first departure of the season.',
		],
		[
			'slug'     => 'kashmir-in-winter-photo-story',
			'title'    => 'Kashmir in winter: a photo story',
			'image'    => 'dal-lake',
			'dest'     => 'kashmir',
			'category' => 'Travel stories',
			'excerpt'  => 'Frozen mornings on Dal Lake, snow in Gulmarg and kahwa by the fire — Kashmir is magic in the cold months.',
		],
	],

	'homepage'     => [
		'hero_heading'        => 'Where to next?',
		'hero_subtitle'       => "Handpicked stays, day-by-day plans and a real human on call 24/7. You pack the bags — we'll handle everything else.",
		'hero_places'         => [
			[ 'image' => 'ladakh-road', 'place' => 'Ladakh.', 'country' => 'Land of High Passes', 'tab_label' => 'Ladakh' ],
			[ 'image' => 'dal-lake', 'place' => 'Kashmir.', 'country' => 'Paradise on Earth', 'tab_label' => 'Kashmir' ],
			[ 'image' => 'rohtang', 'place' => 'Manali.', 'country' => 'Himachal Pradesh', 'tab_label' => 'Manali' ],
			[ 'image' => 'flags', 'place' => 'Spiti.', 'country' => 'The cold desert', 'tab_label' => 'Spiti' ],
			[ 'image' => 'shimla', 'place' => 'Shimla.', 'country' => 'Queen of the Hills', 'tab_label' => 'Shimla' ],
		],
		'why_label'           => "Why we are OG's",
		'why_quote'           => "We started OgTrips because we were tired of *copy-paste holidays*. Every trip we sell is one we've *travelled ourselves* — so yours feels less like a package and more like a story worth telling.",
		'why_cite'            => 'The founders, OgTrips',
		'why_pillars'         => [
			[ 'icon' => 'shield-check', 'title' => 'Trust', 'text' => "Transparent pricing, verified stays and no hidden fees. What's included is listed — and so is what's not.", 'stat_number' => 12, 'stat_suffix' => 'k+', 'stat_label' => 'travellers trust us' ],
			[ 'icon' => 'sparkles', 'title' => 'Experience beyond ordinary', 'text' => 'Sunrise at Pangong, homestays in Spiti, shikara rides on Dal Lake — the moments other tours skip.', 'stat_number' => 120, 'stat_suffix' => '+', 'stat_label' => 'curated experiences' ],
			[ 'icon' => 'headset', 'title' => '24/7 support', 'text' => 'A real human trip captain on WhatsApp before, during and after your trip — any time, any hour.', 'stat_number' => 5, 'stat_suffix' => ' min', 'stat_label' => 'average reply time' ],
		],
		'reviews_label'       => 'Reviews',
		'reviews_heading'     => 'Loved by *12,000+* travellers',
		'reviews_rating'      => 4.9,
		'reviews_count_label' => '2,300+ reviews on Google & Tripadvisor',
		'moments_label'       => '#OgTrips moments',
		'moments_heading'     => 'Tagged by *you*, loved by us',
		'moments_intro'       => 'Real photos and reels from travellers who tagged @ogtrips on Instagram. Tag us — you might be next.',
		'trips_label'         => 'Our OG Trips',
		'trips_heading'       => 'Most-loved *trips* right now',
		'contact_label'       => 'Contact us',
		'contact_heading'     => "Where to *next?* Let's talk.",
		'contact_lead'        => 'Tell us your dates and dream — get a free, personalised itinerary within 24 hours.',
		'form_title'          => 'Plan my trip',
		'form_subtitle'       => 'A trip expert replies within one working day.',
	],

	'settings'     => [
		'phone'              => '+91 98765 43210',
		'whatsapp'           => '+91 98765 43210',
		'email'              => 'hello@ogtrips.com',
		'address'            => 'MG Road, New Delhi',
		'instagram_handle'   => 'ogtrips',
		'hashtag'            => '#WhereToNext',
		'instagram_url'      => 'https://www.instagram.com/',
		'facebook_url'       => 'https://www.facebook.com/',
		'youtube_url'        => 'https://www.youtube.com/',
		'footer_blurb'       => "Trips planned by people who've actually been there. Handpicked stays, honest prices, 24/7 support.",
		'newsletter_enabled' => 0,
		'show_prices'        => 0,
		'booking_trust_text' => 'No payment now · 50% advance to confirm',
	],
];
