<?php
/**
 * DEMO CONTENT — taken from the approved static design. Reviews, handles, prices, phone and
 * address are FAKE placeholders: replace or delete them before launch ("Remove demo content").
 * Photos: Unsplash (free licence), downloaded into the Media Library on import.
 *
 * @package ogtrips-core
 */

defined( 'ABSPATH' ) || exit;

$u = static function ( $id ) {
	return 'https://images.unsplash.com/photo-' . $id . '?auto=format&fit=crop&w=1800&q=78';
};

$img = [
	'bali'       => $u( '1537996194471-e657df975ab4' ),
	'kerala'     => $u( '1602216056096-3b40cc0c9944' ),
	'alps'       => $u( '1476514525535-07fb3b4ae5f1' ),
	'rajasthan'  => $u( '1477587458883-47145ed94245' ),
	'maldives'   => $u( '1514282401047-d79a71a590e8' ),
	'ladakh'     => $u( '1506905925346-21bda4d32df4' ),
	'ubud'       => $u( '1573790387438-4da905039392' ),
	'terraces'   => $u( '1555400038-63f5ba517a47' ),
	'batur'      => $u( '1464822759023-fed622ff2c3b' ),
	'beach'      => $u( '1507525428034-b723cf961d3e' ),
	'uluwatu'    => $u( '1539367628448-4bc5c9d171c8' ),
	'resort'     => $u( '1520250497591-112f2f40a3f4' ),
	'alaya'      => $u( '1566073771259-6a8506099945' ),
	'anantara'   => $u( '1571896349842-33c89424de2d' ),
	'neha'       => $u( '1438761681033-6461ffad8d80' ),
	'priya'      => $u( '1494790108377-be9c29b29330' ),
	'rahul'      => $u( '1507003211169-0a1dd7228f2d' ),
	'sneha'      => $u( '1517841905240-472988babdf9' ),
	'reel1'      => $u( '1530789253388-582c481c54b0' ),
	'road'       => $u( '1469854523086-cc02fe5d8800' ),
	'packing'    => $u( '1488646953014-85cb44e25828' ),
];

$p = static function ( $text ) {
	return '<p>' . $text . '</p>';
};

return [
	'images'       => $img,

	'destinations' => [
		'bali'      => [ 'Bali', 'Temples, rice terraces and hidden beaches — our most-loved island.' ],
		'ladakh'    => [ 'Ladakh', 'High passes, turquoise lakes and monasteries on the roof of India.' ],
		'maldives'  => [ 'Maldives', 'Overwater villas, sandbanks and the clearest water you will ever see.' ],
		'kerala'    => [ 'Kerala', 'Backwaters, tea hills and slow houseboat days in God’s Own Country.' ],
		'rajasthan' => [ 'Rajasthan', 'Forts, palaces and desert sunsets in the land of kings.' ],
	],

	'expert'       => [
		'login'       => 'neha',
		'first_name'  => 'Neha',
		'last_name'   => 'Sharma',
		'description' => "Neha has led 40+ OgTrips departures to Bali since 2019 and still hasn't found a better nasi goreng than the warung behind Ubud market.",
		'photo'       => 'neha',
		'byline_role' => 'OgTrips trip captain',
		'specialty'   => 'Bali specialist',
		'reply_time'  => 'replies in ~5 min',
	],

	'trips'        => [
		[
			'slug'   => 'bali-bliss',
			'title'  => 'Bali Bliss: temples, terraces & hidden beaches',
			'image'  => 'bali',
			'dest'   => 'bali',
			'types'  => [ 'honeymoon', 'culture' ],
			'excerpt' => 'A 7-day Bali itinerary through Ubud, Nusa Penida and Uluwatu with handpicked stays, private transfers and a day-by-day plan.',
			'content' => $p( "A week that balances Bali's two souls — the green, spiritual heart around Ubud and the dramatic cliffs of the south. Water temples, a sunrise volcano trek, a day on Nusa Penida and the Kecak fire dance as the sun sets over Uluwatu." ),
			'fields' => [
				'title_display'   => 'Bali Bliss: temples, terraces *&* hidden beaches',
				'short_title'     => 'Bali Bliss',
				'location_label'  => 'Bali, Indonesia',
				'badge'           => '#1 Bestseller',
				'badge_style'     => 'sun',
				'badge_icon'      => 'award',
				'is_bestseller'   => 1,
				'bestseller_rank' => 1,
				'route_stops'     => [
					[ 'label' => 'Ubud', 'days' => 'Day 1–3' ],
					[ 'label' => 'Kintamani', 'days' => 'Day 3' ],
					[ 'label' => 'Seminyak', 'days' => 'Day 4' ],
					[ 'label' => 'Nusa Penida', 'days' => 'Day 5' ],
					[ 'label' => 'Uluwatu', 'days' => 'Day 6–7' ],
				],
				'highlights'      => [
					[ 'icon' => 'sunrise', 'text' => 'Sunrise trek on Mount Batur' ],
					[ 'icon' => 'sprout', 'text' => 'Tegallalang rice terraces' ],
					[ 'icon' => 'droplets', 'text' => 'Tirta Empul water temple' ],
					[ 'icon' => 'waves', 'text' => 'Kelingking Beach, Nusa Penida' ],
					[ 'icon' => 'flame', 'text' => 'Kecak fire dance at Uluwatu' ],
					[ 'icon' => 'utensils', 'text' => 'Seafood dinner on Jimbaran beach' ],
				],
				'duration_days'   => 7,
				'duration_nights' => 6,
				'group_min'       => 2,
				'group_max'       => 12,
				'best_time'       => 'April – October',
				'pace'            => 'easy-moderate',
				'stays_label'     => '4★ villas & resorts',
				'rating'          => 4.9,
				'review_count'    => 312,
				'price_from'      => 54999,
				'price_original'  => 62000,
				'offer_label'     => 'Early-bird',
				'departures'      => [
					[ 'date' => '20261114', 'seats_left' => 6 ],
					[ 'date' => '20261205', 'seats_left' => 9 ],
					[ 'date' => '20270109', 'seats_left' => 12 ],
				],
				'days'            => [
					[ 'title' => 'Arrive in paradise, transfer to Ubud', 'location' => 'Denpasar → Ubud · 1.5 hr drive', 'image' => 'ubud', 'description' => $p( 'Your trip captain meets you at Ngurah Rai Airport with a flower garland and cold coconut. Drive through the countryside to your private pool villa in the jungle. Evening free to wander Ubud market and the Monkey Forest road.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Alaya Ubud' ], [ 'icon' => 'utensils', 'text' => 'Welcome dinner' ], [ 'icon' => 'car', 'text' => 'Private transfer' ] ] ],
					[ 'title' => 'Rice terraces, coffee & a water temple', 'location' => 'Tegallalang · Tirta Empul', 'image' => 'terraces', 'description' => $p( 'Beat the crowds at Tegallalang with an early start, then a slow coffee tasting at a family plantation. Afternoon purification ritual at Tirta Empul and a golden-hour walk along Campuhan Ridge.' ), 'tags' => [ [ 'icon' => 'coffee', 'text' => 'Breakfast' ], [ 'icon' => 'car', 'text' => 'Private car & guide' ] ] ],
					[ 'title' => 'Sunrise above the clouds on Mount Batur', 'location' => 'Kintamani · 1,717 m', 'image' => 'batur', 'description' => $p( 'A 2 AM pickup for a guided trek to the summit in time for sunrise over Lake Batur. Breakfast is cooked in volcanic steam. Afternoon soak in natural hot springs, then back to Ubud to rest.' ), 'tags' => [ [ 'icon' => 'mountain', 'text' => 'Guided trek' ], [ 'icon' => 'coffee', 'text' => 'Breakfast' ] ] ],
					[ 'title' => 'To the coast, sunset at Tanah Lot', 'location' => 'Ubud → Seminyak', 'image' => 'beach', 'description' => $p( "Check in to your beachfront resort in Seminyak, with a stop at the Tanah Lot sea temple for sunset. Evening at one of the island's best beach clubs." ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'The Legian' ], [ 'icon' => 'coffee', 'text' => 'Breakfast' ] ] ],
					[ 'title' => 'Island day on Nusa Penida', 'location' => 'Kelingking · Crystal Bay', 'image' => 'maldives', 'description' => $p( "Fast boat across to Nusa Penida for Kelingking Beach, Broken Beach and Angel's Billabong, finishing with snorkelling among manta rays at Crystal Bay." ), 'tags' => [ [ 'icon' => 'ship', 'text' => 'Fast boat' ], [ 'icon' => 'utensils', 'text' => 'Lunch' ] ] ],
					[ 'title' => 'Cliff temples & the Kecak fire dance', 'location' => 'Uluwatu · Jimbaran', 'image' => 'uluwatu', 'description' => $p( 'A slow morning by the pool. In the afternoon, Uluwatu temple on its 70 m cliff, the Kecak dance at sunset, and a candlelit seafood dinner on Jimbaran beach.' ), 'tags' => [ [ 'icon' => 'ticket', 'text' => 'Kecak tickets' ], [ 'icon' => 'utensils', 'text' => 'Seafood dinner' ] ] ],
					[ 'title' => 'Slow breakfast, fond farewells', 'location' => 'Seminyak → Airport', 'image' => 'resort', 'description' => $p( 'Free time for last-minute shopping or one final swim, then a private transfer to the airport for your flight home.' ), 'tags' => [ [ 'icon' => 'coffee', 'text' => 'Breakfast' ], [ 'icon' => 'car', 'text' => 'Airport transfer' ] ] ],
				],
				'stays'           => [
					[ 'name' => 'Alaya Resort Ubud', 'nights' => 3, 'room' => 'Pool villa', 'image' => 'alaya' ],
					[ 'name' => 'The Legian Seminyak', 'nights' => 2, 'room' => 'Ocean suite', 'image' => 'resort' ],
					[ 'name' => 'Anantara Uluwatu', 'nights' => 1, 'room' => 'Cliff view', 'image' => 'anantara' ],
				],
				'incl_icons'      => [ 'bed-double', 'utensils', 'car', 'ticket' ],
				'included'        => [ '6 nights in handpicked 4★ villas & resorts', 'Daily breakfast + 3 signature meals', 'All transfers in a private AC car', 'Nusa Penida fast boat & island tour', 'Entry tickets & English-speaking guides', '24/7 trip captain on WhatsApp' ],
				'excluded'        => [ 'International flights', 'Visa on arrival & tourist levy', 'Travel insurance', 'Personal expenses & tips', 'Meals not mentioned' ],
				'gallery'         => [ 'bali', 'terraces', 'ubud', 'uluwatu', 'beach', 'resort' ],
				'faqs'            => [
					[ 'question' => 'Can I customise this itinerary?', 'answer' => $p( 'Absolutely. Add days, upgrade stays, swap activities or travel privately — every journey is a starting point. Mention it in your enquiry.' ) ],
					[ 'question' => 'How hard is the Mount Batur trek?', 'answer' => $p( "It's a moderate two-hour climb in the dark. Anyone with basic fitness can do it — guides set a comfortable pace, and you can skip it for a sunrise café instead." ) ],
					[ 'question' => "What's the cancellation policy?", 'answer' => $p( 'Free cancellation up to 30 days before departure, 50% refund between 30 and 15 days, and no refund within 15 days.' ) ],
					[ 'question' => 'Do I need a visa for Bali?', 'answer' => $p( 'Indian passport holders can get a visa on arrival or an e-VOA online. See our Bali travel guide for current rules.' ) ],
				],
			],
		],
		[
			'slug'    => 'leh-ladakh-road-trip',
			'title'   => 'Leh–Ladakh road trip with Pangong & Nubra',
			'image'   => 'ladakh',
			'dest'    => 'ladakh',
			'types'   => [ 'adventure', 'friends' ],
			'excerpt' => 'Eight days over the highest passes to Nubra Valley and Pangong Lake, with acclimatisation built in.',
			'content' => $p( 'Eight days on the roof of India — monasteries above Leh, the dunes of Nubra, a night by the impossible blue of Pangong Lake and passes higher than most mountains. Acclimatisation days are built in, so you feel the views, not the altitude.' ),
			'fields'  => [
				'short_title' => 'Leh–Ladakh', 'location_label' => 'Ladakh, India', 'badge' => 'Selling fast', 'badge_style' => 'coral', 'badge_icon' => 'flame',
				'is_bestseller' => 1, 'bestseller_rank' => 2, 'duration_days' => 8, 'duration_nights' => 7, 'group_min' => 4, 'group_max' => 14,
				'best_time' => 'June – September', 'pace' => 'moderate-challenging', 'stays_label' => 'Boutique hotels & camps', 'rating' => 4.8, 'review_count' => 204,
				'price_from' => 38500, 'incl_icons' => [ 'bed-double', 'utensils', 'car', 'tent' ],
				'route_stops' => [ [ 'label' => 'Leh', 'days' => 'Day 1–3' ], [ 'label' => 'Nubra', 'days' => 'Day 4–5' ], [ 'label' => 'Pangong', 'days' => 'Day 6' ], [ 'label' => 'Leh', 'days' => 'Day 7–8' ] ],
				'highlights' => [ [ 'icon' => 'mountain', 'text' => 'Khardung La, one of the highest roads' ], [ 'icon' => 'tent', 'text' => 'Lakeside camp at Pangong' ], [ 'icon' => 'sunrise', 'text' => 'Sunrise prayers at Thiksey' ] ],
				'departures' => [ [ 'date' => '20270606', 'seats_left' => 8 ], [ 'date' => '20270704', 'seats_left' => 10 ] ],
				'days' => [
					[ 'title' => 'Fly into Leh, rest and acclimatise', 'location' => 'Leh · 3,500 m', 'image' => 'ladakh', 'description' => $p( 'Airport pickup and a slow day to let your body adjust. Evening stroll to Shanti Stupa for sunset.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Boutique hotel' ], [ 'icon' => 'car', 'text' => 'Airport transfer' ] ] ],
					[ 'title' => 'Monasteries of the Indus valley', 'location' => 'Thiksey · Hemis', 'image' => 'road', 'description' => $p( 'Morning prayers at Thiksey, Hemis monastery and the confluence of the Indus and Zanskar.' ), 'tags' => [ [ 'icon' => 'coffee', 'text' => 'Breakfast' ] ] ],
					[ 'title' => 'Over Khardung La to Nubra', 'location' => 'Leh → Nubra', 'image' => 'batur', 'description' => $p( 'Cross one of the highest motorable passes to the cold desert of Nubra and its double-humped camels.' ), 'tags' => [ [ 'icon' => 'tent', 'text' => 'Desert camp' ] ] ],
				],
				'included' => [ '7 nights in hotels and camps', 'Breakfast and dinner daily', 'Private SUV with driver', 'Inner-line permits' ],
				'excluded' => [ 'Flights to Leh', 'Travel insurance', 'Lunches' ],
				'gallery'  => [ 'ladakh', 'road', 'batur' ],
				'faqs'     => [ [ 'question' => 'Is the altitude a problem?', 'answer' => $p( 'We plan two rest days in Leh before going higher. Drink water, go slow, and you will be fine.' ) ] ],
			],
		],
		[
			'slug'    => 'maldives-overwater-escape',
			'title'   => 'Maldives overwater villa escape',
			'image'   => 'maldives',
			'dest'    => 'maldives',
			'types'   => [ 'honeymoon' ],
			'excerpt' => 'Five days in an overwater villa on Baa Atoll with a private sandbank dinner.',
			'content' => $p( 'Five slow days in an overwater villa on Baa Atoll — snorkelling with manta rays, a sunset dolphin cruise and a private dinner on a sandbank under the stars.' ),
			'fields'  => [
				'short_title' => 'Maldives overwater escape', 'location_label' => 'Baa Atoll, Maldives', 'badge' => 'Honeymoon pick', 'badge_style' => 'plain', 'badge_icon' => 'heart',
				'is_bestseller' => 1, 'bestseller_rank' => 3, 'duration_days' => 5, 'duration_nights' => 4, 'group_min' => 2, 'group_max' => 2,
				'best_time' => 'November – April', 'pace' => 'easy', 'stays_label' => '5★ overwater villa', 'rating' => 5, 'review_count' => 148,
				'price_from' => 124000, 'incl_icons' => [ 'bed-double', 'utensils', 'plane', 'waves' ],
				'highlights' => [ [ 'icon' => 'waves', 'text' => 'Snorkel with manta rays' ], [ 'icon' => 'sailboat', 'text' => 'Sunset dolphin cruise' ], [ 'icon' => 'heart', 'text' => 'Private sandbank dinner' ] ],
				'days' => [
					[ 'title' => 'Seaplane to your overwater villa', 'location' => 'Malé → Baa Atoll', 'image' => 'maldives', 'description' => $p( 'A 40-minute seaplane ride over the atolls to your villa, with a ladder straight into the lagoon.' ), 'tags' => [ [ 'icon' => 'plane', 'text' => 'Seaplane' ] ] ],
					[ 'title' => 'Manta rays at Hanifaru Bay', 'location' => 'Baa Atoll', 'image' => 'beach', 'description' => $p( 'Guided snorkel in the UNESCO biosphere, then a lazy afternoon at the spa.' ), 'tags' => [ [ 'icon' => 'waves', 'text' => 'Snorkel trip' ] ] ],
				],
				'included' => [ '4 nights in an overwater villa', 'All meals', 'Return seaplane transfers' ],
				'excluded' => [ 'International flights', 'Green tax' ],
				'gallery'  => [ 'maldives', 'beach', 'resort' ],
			],
		],
		[
			'slug'    => 'kerala-calling',
			'title'   => 'Kerala calling: Munnar, Thekkady & houseboat',
			'image'   => 'kerala',
			'dest'    => 'kerala',
			'types'   => [ 'family' ],
			'excerpt' => 'Tea hills, spice gardens and a night on a private houseboat — six easy-paced days.',
			'content' => $p( 'Six easy-paced days through tea hills, spice gardens and wildlife, ending with a night on a private houseboat drifting through the backwaters of Alleppey.' ),
			'fields'  => [
				'short_title' => 'Kerala backwaters & hills', 'location_label' => 'Kerala, India', 'badge' => 'Family favourite', 'badge_style' => 'plain', 'badge_icon' => 'baby',
				'is_bestseller' => 1, 'bestseller_rank' => 4, 'duration_days' => 6, 'duration_nights' => 5, 'group_min' => 2, 'group_max' => 10,
				'best_time' => 'September – March', 'pace' => 'easy', 'stays_label' => 'Resorts & houseboat', 'rating' => 4.8, 'review_count' => 176,
				'price_from' => 27500, 'incl_icons' => [ 'bed-double', 'utensils', 'car', 'sailboat' ],
				'highlights' => [ [ 'icon' => 'sprout', 'text' => 'Tea estates of Munnar' ], [ 'icon' => 'sailboat', 'text' => 'Private houseboat night' ], [ 'icon' => 'utensils', 'text' => 'Kerala sadya on a banana leaf' ] ],
				'days' => [
					[ 'title' => 'Kochi to the hills of Munnar', 'location' => 'Kochi → Munnar', 'image' => 'kerala', 'description' => $p( 'A scenic drive past waterfalls into the tea country.' ), 'tags' => [ [ 'icon' => 'car', 'text' => 'Private car' ] ] ],
					[ 'title' => 'Houseboat day on the backwaters', 'location' => 'Alleppey', 'image' => 'terraces', 'description' => $p( 'Board your private houseboat for a slow day of village life, fresh fish curry and sunset on the water.' ), 'tags' => [ [ 'icon' => 'sailboat', 'text' => 'Houseboat' ], [ 'icon' => 'utensils', 'text' => 'All meals' ] ] ],
				],
				'included' => [ '5 nights in resorts and a houseboat', 'Daily breakfast', 'Private car and driver' ],
				'excluded' => [ 'Flights', 'Entry tickets' ],
				'gallery'  => [ 'kerala', 'terraces' ],
			],
		],
		[
			'slug'    => 'royal-rajasthan',
			'title'   => 'Royal Rajasthan: Jaipur, Jodhpur & Udaipur',
			'image'   => 'rajasthan',
			'dest'    => 'rajasthan',
			'types'   => [ 'culture', 'family' ],
			'excerpt' => 'Forts, palaces and lake sunsets across three royal cities in six days.',
			'content' => $p( 'Six days of forts, palaces and bazaars — the pink city of Jaipur, the blue lanes of Jodhpur and a sunset boat ride on Lake Pichola in Udaipur.' ),
			'fields'  => [
				'short_title' => 'Royal Rajasthan', 'location_label' => 'Jaipur · Udaipur', 'duration_days' => 6, 'duration_nights' => 5, 'group_min' => 2, 'group_max' => 12,
				'best_time' => 'October – March', 'pace' => 'moderate', 'stays_label' => 'Heritage havelis', 'rating' => 4.7, 'review_count' => 98,
				'price_from' => 29999, 'incl_icons' => [ 'bed-double', 'utensils', 'car', 'ticket' ],
				'highlights' => [ [ 'icon' => 'landmark', 'text' => 'Amber Fort at sunrise' ], [ 'icon' => 'sailboat', 'text' => 'Lake Pichola boat ride' ], [ 'icon' => 'camera', 'text' => 'Blue lanes of Jodhpur' ] ],
				'days' => [
					[ 'title' => 'Pink city welcome', 'location' => 'Jaipur', 'image' => 'rajasthan', 'description' => $p( 'Check in to a heritage haveli and an evening walk through the bazaars.' ), 'tags' => [ [ 'icon' => 'bed-double', 'text' => 'Heritage haveli' ] ] ],
				],
				'included' => [ '5 nights in heritage hotels', 'Daily breakfast', 'Private car and guides' ],
				'excluded' => [ 'Flights', 'Camera fees' ],
				'gallery'  => [ 'rajasthan' ],
			],
		],
	],

	'reviews'      => [
		[ 'Priya Sharma', 'Mumbai', '20260601', 'google', 'priya', 'bali-bliss', 'Every transfer was on time and every hotel was better than the photos. It felt like travelling with a friend who knows everyone on the island.' ],
		[ 'Rahul Kapoor', 'Delhi', '20260701', 'tripadvisor', 'rahul', 'leh-ladakh-road-trip', 'Ladakh was a dream. The acclimatisation days were planned perfectly and our driver knew every secret viewpoint. Already booking the next one.' ],
		[ 'Ananya & Mihir', 'Bengaluru', '20260501', 'google', 'neha', 'maldives-overwater-escape', 'Our honeymoon was flawless — they even surprised us with a private dinner on a sandbank. The 24/7 WhatsApp support is genuinely 24/7.' ],
		[ 'Sneha Iyer', 'Pune', '20260401', 'google', 'sneha', 'kerala-calling', 'Travelled with my parents and two kids — the pace was just right for everyone. The houseboat night was the highlight of our year.' ],
	],

	'moments'      => [
		[ '@wanderwithriya', 'reel1', 'big', 'video', '0:42', '12.4k', '98k' ],
		[ '@arjun.clicks', 'terraces', 'normal', 'image', '', '2.1k', '' ],
		[ '@ladakh.diaries', 'ladakh', 'tall', 'video', '0:28', '8.7k', '' ],
		[ '@mihir_ananya', 'maldives', 'normal', 'image', '', '5.3k', '' ],
		[ '@roadtrip.rahul', 'road', 'wide', 'image', '', '3.9k', '' ],
		[ '@desi.nomad', 'rajasthan', 'normal', 'image', '', '1.8k', '' ],
		[ '@sneha.travels', 'beach', 'wide', 'video', '1:05', '6.2k', '' ],
		[ '@kavya.goes', 'uluwatu', 'normal', 'image', '', '2.6k', '' ],
	],

	'guides'       => [
		[
			'slug'    => 'bali-travel-guide',
			'title'   => 'The complete Bali guide for *first-timers*',
			'image'   => 'uluwatu',
			'dest'    => 'bali',
			'topic'   => 'destination-guide',
			'excerpt' => 'Where to stay in Bali, how to get around, what it costs, visa rules and the best time to visit — from the OgTrips trip captains.',
			'fields'  => [
				'cover_caption'    => "Early mornings are the secret to Bali's most famous spots.",
				'glance_best_time' => 'April – October',
				'glance_budget'    => '₹4,000 – ₹15,000',
				'glance_length'    => '7 – 10 days',
				'glance_visa'      => 'On arrival / e-VOA',
			],
			'blocks'  => 'bali',
		],
		[
			'slug'    => 'pack-ten-days-carry-on',
			'title'   => 'How to pack for ten days in a carry-on',
			'image'   => 'packing',
			'dest'    => '',
			'topic'   => 'travel-tips',
			'excerpt' => 'The trip captains’ checklist for travelling light without missing a thing.',
			'blocks'  => 'short',
		],
		[
			'slug'    => 'best-time-to-visit-ladakh',
			'title'   => 'Best time to visit Ladakh, month by month',
			'image'   => 'batur',
			'dest'    => 'ladakh',
			'topic'   => 'seasonal',
			'excerpt' => 'When the passes open, when the lakes freeze and when to go for festivals.',
			'blocks'  => 'short',
		],
		[
			'slug'    => 'kerala-houseboat-or-homestay',
			'title'   => 'Kerala backwaters: houseboat or homestay?',
			'image'   => 'kerala',
			'dest'    => 'kerala',
			'topic'   => 'destination-guide',
			'excerpt' => 'Two very different ways to see the backwaters — and how to choose.',
			'blocks'  => 'short',
		],
	],

	'homepage'     => [
		'hero_heading'        => 'Where to next?',
		'hero_subtitle'       => "Handpicked stays, day-by-day plans and a real human on call 24/7. You pack the bags — we'll handle everything else.",
		'hero_places'         => [
			[ 'image' => 'bali', 'place' => 'Bali.', 'country' => 'Indonesia', 'tab_label' => 'Bali' ],
			[ 'image' => 'kerala', 'place' => 'Kerala.', 'country' => 'India', 'tab_label' => 'Kerala' ],
			[ 'image' => 'alps', 'place' => 'the Alps.', 'country' => 'Switzerland', 'tab_label' => 'Swiss Alps' ],
			[ 'image' => 'rajasthan', 'place' => 'Rajasthan.', 'country' => 'India', 'tab_label' => 'Rajasthan' ],
			[ 'image' => 'maldives', 'place' => 'Maldives.', 'country' => 'Indian Ocean', 'tab_label' => 'Maldives' ],
		],
		'why_label'           => "Why we are OG's",
		'why_quote'           => "We started OgTrips because we were tired of *copy-paste holidays*. Every trip we sell is one we've *travelled ourselves* — so yours feels less like a package and more like a story worth telling.",
		'why_cite'            => 'The founders, OgTrips',
		'why_pillars'         => [
			[ 'icon' => 'shield-check', 'title' => 'Trust', 'text' => "Transparent pricing, verified stays and no hidden fees. What's included is listed — and so is what's not.", 'stat_number' => 12, 'stat_suffix' => 'k+', 'stat_label' => 'travellers trust us' ],
			[ 'icon' => 'sparkles', 'title' => 'Experience beyond ordinary', 'text' => 'Sunrise volcano treks, private sandbank dinners, homestays with local families — the moments other tours skip.', 'stat_number' => 120, 'stat_suffix' => '+', 'stat_label' => 'curated experiences' ],
			[ 'icon' => 'headset', 'title' => '24/7 support', 'text' => 'A real human trip captain on WhatsApp before, during and after your trip — any time zone, any hour.', 'stat_number' => 5, 'stat_suffix' => ' min', 'stat_label' => 'average reply time' ],
		],
		'reviews_label'       => 'Reviews',
		'reviews_heading'     => 'Loved by *12,000+* travellers',
		'reviews_rating'      => 4.9,
		'reviews_count_label' => '2,300+ reviews on Google & Tripadvisor',
		'moments_label'       => '#OgTrips moments',
		'moments_heading'     => 'Tagged by *you*, loved by us',
		'moments_intro'       => 'Real photos and reels from travellers who tagged @ogtrips on Instagram. Tag us — you might be next.',
		'trips_label'         => 'Our OG Trips',
		'trips_heading'       => 'Most-loved *trips* right now',
		'contact_label'       => 'Contact us',
		'contact_heading'     => "Where to *next?* Let's talk.",
		'contact_lead'        => 'Tell us your dates and dream — get a free, personalised itinerary within 24 hours.',
		'form_title'          => 'Plan my trip',
		'form_subtitle'       => 'A trip expert replies within one working day.',
	],

	'settings'     => [
		'phone'              => '+91 98765 43210',
		'whatsapp'           => '+91 98765 43210',
		'email'              => 'hello@ogtrips.com',
		'address'            => 'MG Road, New Delhi',
		'instagram_handle'   => 'ogtrips',
		'hashtag'            => '#WhereToNext',
		'instagram_url'      => 'https://www.instagram.com/',
		'facebook_url'       => 'https://www.facebook.com/',
		'youtube_url'        => 'https://www.youtube.com/',
		'footer_blurb'       => "Trips planned by people who've actually been there. Handpicked stays, honest prices, 24/7 support.",
		'newsletter_enabled' => 0,
		'booking_trust_text' => 'No payment now · Free cancellation',
	],
];
